### ISSUE TITLE
Which Firmware is the right

### ISSUE THREAD

**Issue by JanekHinderks** [vertigo235/Build-Prusa-LA-15#1]
Hei, i dont know if this is the right way to ask you about the Firmware ( but I dont know where I can ask you :)  ) 
I have a question about the right Firmware.
I have a mk3 with bmg extruder
In the next days I will upgrade to bear Frame and Mk3s sensor with mmu2s.
Can you help me to choose the right Firmware please :)

Should i use this one:
FW371-Build1558898469-1_75mm_MK3S-BMG-16-EINSy10a-E3Dv6full.hex

And whats is with the "bear frame" should it work? 

Thanks a lot. 

Best regards.

**Comment by vertigo235** [comment]
Yes that's correct, the frame is irrelevant, the "BEAR" versions are for the bear extruder, and you have the Bondtech Extruder, so the "BMG" is the correct one.

**Comment by JanekHinderks** [comment]
Thanks a lot :)
