### ISSUE TITLE
mk2 with bear extruder

### ISSUE THREAD

**Issue by jtktam** [vertigo235/Build-Prusa-LA-15#10]
Hi

I just tried to compile 3.7.2 final for my mk2 haribo with bear extruder 

(the only change i need is to make max z 220)

1. i made a copy of 1_75mm_MK2-RAMBo13a-E3Dv6full.h
2. renamed it Configuration_prusa.h
3. made the max z change to 220
4. compile was fine
5. upload was fine

when it rebooted, the display was all scrambled and it was trying to jam the x carriage to the right while moving up in z

i was able to reset and flash back to know good version (3.0.12) and all is well

any idea / steps i might have missed?

**Comment by vertigo235** [comment]
MK2 is not supported by this branch, Prusa maintains a separate branch for MK2.  Only MK2.5 is supported at this time.
