### ISSUE TITLE
Chose pei types not in menu

### ISSUE THREAD

**Issue by FredMk3** [vertigo235/Build-Prusa-LA-15#11]
Hi and thanks for your good work.

I see a feature of last build not good on your last firmware for stock mk3s. 
I use FW380-Build1567793523-1_75mm_MK3S-EINSy10a-E3Dv6full.hex
I not see in menu the choice of sheets pei. 
Other see good and work a charm.

**Comment by vertigo235** [comment]
It should work, you have to first set the sheets up under the settings

Settings -> HW Setup -> Steel Sheets

Once you have created the sheets you should be able to cycle through them on the main screen.

**Comment by FredMk3** [comment]
Ohhh my God.. 
Sorry it work effectively. All is fine, thanks
