### ISSUE TITLE
LDO OLED Support

### ISSUE THREAD

**Issue by j00sef** [vertigo235/Build-Prusa-LA-15#12]
Sorry, I'm not sure where to put this but I just recently got a LDO OLED display and the firmware works great but it doesn't play well with that particular display. Is there anyway you can add support for this.

**Comment by vertigo235** [comment]
Do you have info on what changes are required to support the OLED display?

**Comment by vertigo235** [comment]
I see master 3D-gussner has a branch with the changes. I’ll see if I can cherry-pick his work. What variants would you need support for @j00sef ?

https://github.com/3d-gussner/Prusa-Firmware/tree/MK3_WEH002004_OLED?fbclid=IwAR0p9sJ1NUdz7W0ZhNwJ079qPWotEVvYsGENPNIXAsAuSKZK_WuK6Il5gqM

**Comment by vertigo235** [comment]
https://github.com/3d-gussner/Prusa-Firmware/tree/MK3_WEH002004_OLED?fbclid=IwAR0p9sJ1NUdz7W0ZhNwJ079qPWotEVvYsGENPNIXAsAuSKZK_WuK6Il5gqM

**Comment by j00sef** [comment]
I looked at his work on implementing it but got confused looking through the code.

The variants I would use it for would be the mk3s_bondtech_silverpsu, mk3s_bondtech_sliceht, mk3s_bear_silverpsu, and mk2.5s_bondtech_e3dv6

And thanks man! I appreciate your hard work on this. Do you have a Patreon or similar?

**Comment by 3d-gussner** [comment]
@j00sef Sorry you got confused going through the code.
Some `ifdef WEH002004_OLED` may look unnecessary but as we didn't get a lot of information from Winstar neither from LDO it took lot of test to get timing and delay correctly for the display.
Funny is that I flashed the OLED firmware on a LCD printer and it worked just fine.

**Comment by brownie-21** [comment]
> I see master 3D-gussner has a branch with the changes. I’ll see if I can cherry-pick his work. What variants would you need support for @j00sef ?
> 
> https://github.com/3d-gussner/Prusa-Firmware/tree/MK3_WEH002004_OLED?fbclid=IwAR0p9sJ1NUdz7W0ZhNwJ079qPWotEVvYsGENPNIXAsAuSKZK_WuK6Il5gqM

Can you not just add this to all builds as the changes allow the FW to work on both LCD and OLED?
Failing that I would appreciate a mk3 BMG build.

Looking at the comparisons between @3d-gussner OLED branch and non OLED on github (linked below)  these should be the only required changes. I have tried to implete these but get an error while compiling but i'm a bit of an FW NOOB.

https://github.com/prusa3d/Prusa-Firmware/compare/MK3...3d-gussner:MK3_WEH002004_OLED

**Comment by brownie-21** [comment]
Update- I've compiled a working stable version by using the ultralcd.cpp and lcd.cpp files from 3d-gussener and also adding the OLED definition to configuration_prusa.h. I've also tested it on my LCD and confirm it works on both.

**Comment by j00sef** [comment]
@brownie-21 I was able to compile after making changes to the ultralcd.cpp and lcd.cpp as well. But when I flashed it over to my mk3s bt slice variant it doesn't work. I just get wild characters everywhere. Is there something different you did other than changing those 3 files?

**Comment by vertigo235** [comment]
Sorry this fell off my radar , I’ll see if I can create the variant soon. I wish I had an OLED screen and I would have done this already :)

**Comment by j00sef** [comment]
@vertigo235 no worries man. I'll order you one if you really want it. lol

**Comment by vertigo235** [comment]
I have an OLED screen now! I will try to work this in and test soon.

**Comment by vertigo235** [comment]
Work has moved to my Prusa FW fork now that LA 1.5 is included in 3.9.0

See Issue https://github.com/vertigo235/Prusa-Firmware/issues/8
