### ISSUE TITLE
Update Mosquito Variants to Include modified MMU2 Load Sequence

### ISSUE THREAD

**Issue by lordnibbler22** [vertigo235/Build-Prusa-LA-15#13]
Hello vertigo235,

i am currently using Bondtechs FW for my BMG + Mosquito Magnum + Slice HT.

The FW works good but i am missing LA1.5

Is it possible that you extend your FW variants with this setup? :)

**MK3s Mosquito Magnum with high temperature thermistor (SliceE_HT)**

    #define CUSTOM_MENDEL_NAME "Bondtech-MM MK3s-HT"

    #define BONDTECH_MOSQUITO_MAGNUM

    #define HEATER_0_MINTEMP 5

    #define DEFAULT_AXIS_STEPS_PER_UNIT {100,100,3200/8,415}

    #define TMC2130_USTEPS_E 16

    #define Z_MAX_POS 205

    #define LOAD_FILAMENT_1 "G1 E80 F400"

    #define UNLOAD_FILAMENT_1 "G1 E-95 F7000"

    #define FILAMENTCHANGE_FINALRETRACT -95

    #define FILAMENTCHANGE_FIRSTFEED 80

    #elif defined(BONDTECH_MOSQUITO_MAGNUM) current_position[E_AXIS] += 62; //Bondtech_Mosquito_Magnum 62mm from drive gear to melt zone

    #elif defined(BONDTECH_MOSQUITO_MAGNUM) current_position[E_AXIS] -= 54; // Pull back 54mm, 8 mm below drive gear

    #elif defined(BONDTECH_MOSQUITO_MAGNUM) current_position[E_AXIS] += 18.4f; //Bondtech Mosquito Magnum 4 mm longer t melt zone

    #elif defined(BONDTECH_MOSQUITO_MAGNUM) current_position[E_AXIS] += 21.4f; //7mm further through Mosquito Magnum heat block

https://github.com/BondtechAB/Bondtech_Prusa_i3/tree/master/Firmware/3.8.1

**Comment by vertigo235** [comment]
There is already a variant for the Slice thermistor, it's labeled SliceHT, the additional bits at the bottom there are not yet included. I believe those are only important if you are using the MMU2S, it's for the MMU2S load sequence to make sure the filament path is clear.

**Comment by lordnibbler22** [comment]
thx for the info!

**Comment by vertigo235** [comment]
Hey @lordnibbler22 I finally made these changes now that bontech has a fork and I Was able to easily pick out the changes, do you want to test? 

I'm moving issues and discussion to my prusa fw fork now that la 1.5 is included in 3.9.0

https://github.com/vertigo235/Prusa-Firmware/issues/7
