### ISSUE TITLE
MK3S FW for BMG with 0.9 stepper

### ISSUE THREAD

**Issue by libxmike** [vertigo235/Build-Prusa-LA-15#14]
There is BMG FW with "16", what does it mean? 
Is there also FW for MK3S with Silver PSU, BMG and 0.9 extruded stepper? 
If not, is there a way to adjust the one that is available?

**Comment by vertigo235** [comment]
It just means that the E motor defaults to 16 microsteps. 

If you want to use a .9 degree stepper (I don't recommend it), you would want to use 8 microsteps. 

M350 E8 ; sets microstepping to 1/8
M92 E415; sets esteps to 415
M500 ; save to eeprom

You can verify your current settings by issuing
M503

**Comment by libxmike** [comment]
thanks!
I already have on my MK3S's BMG LDO 0.9, Bear still have 1.8, I still have few 0.9 LDO's but may skip it on Bear BMG when I will do the BMG upgrade.

btw, why don't you recommend it?

**Comment by vertigo235** [comment]
I tried the .9 stepper with the Prusa FW and it was more trouble than it was worth seemed to miss steps etc, even with 8 microsteps it still seemed to be an issue.  The 1.8 stepper just works with 16 microsteps.  I do use the .9 stepper with klipper however. 

You can probably tune it to work but I didn't see the point, just don't expect it to be an improvement.

**Comment by wavexx** [comment]
On Sun, Jan 12 2020, Josh Jones wrote:
> I tried the .9 stepper with the Prusa FW and it was more trouble than
> it was worth seemed to miss steps etc, even with 8 microsteps it still
> seemed to be an issue. The 1.8 stepper just works with 16 microsteps.
> I do use the .9 stepper with klipper however.

I'm using the BMG with a .9 LDO, 1/16 microstepping and E steps set to 830.

Compared to a 1.8 stepper, you loose a bit of max speed.
Max E feedrate should not exceed 35mm/s, and can be defined on the
variant file with DEFAULT_MAX_FEEDRATE (and on your slicer setting too).

This is not an issue typically for a .4 nozzle, but it's probably too
slow when paired with an MMU unit which has a ton of hardcoded behavior
expecting to reach higher unloading speeds.
