### ISSUE TITLE
Safety timeout exceeded

### ISSUE THREAD

**Issue by WarrenSchultz** [vertigo235/Build-Prusa-LA-15#3]
Have a weird, repeatable issue, latest version as of 20190605.

Preheat (PETG) ->Filament change -> Changed the filament -> [Did filament change ok?] Yes -> Safety timeout, shutdown of heaters.

**Comment by vertigo235** [comment]
Were you able to confirm this issue doesn't exist on stock prusa 3.7.1 FW?

If you can reproduce it there, it's not related to the LA 1.5 changes, but if you can't reproduce then I would ask you to open an issue on @wavexx 's repo where he is the actual developer for the LA 1.5 fork.  I'm just using this repository as a staging area to build a bunch of versions.

**Comment by vertigo235** [comment]
This is the issue to provide feedback to the LA 1.5 code. 

https://github.com/wavexx/Prusa-Firmware/issues/1

**Comment by WarrenSchultz** [comment]
I'll see what happens in stock, and go from there. Thanks.

**Comment by wavexx** [comment]
I'm curious about the results. I see no reason this would be a result of the LA changes

**Comment by WarrenSchultz** [comment]
I haven’t had this happen on stock or on the main vertigo branch. I’ll switch back to the LA1.5 branch tonight and see if it returns. Thanks.
