### ISSUE TITLE
LA1.5 with mk3s and mmu2s stock

### ISSUE THREAD

**Issue by GigiGipo** [vertigo235/Build-Prusa-LA-15#4]
Hi! I tried the new firmware with good results but I have problems with loading the fifth filament. If load 5 stops however at 4. It depends on the fw or something wrong?

**Comment by vertigo235** [comment]
What do you mean when you load the 5th filament it stops at 4?  

I'm using MMU2S with this FW and I don't recall having an issue like this. Regardless I don't think this would be related to the LA15 changes that have been made. You do not have this issue with stock 3.7.1 FW?

Can you share your GCODE?

**Comment by GigiGipo** [comment]
if I try to load the filament 5 the mmu stops at 4. The first 4 positions ok. Before the new firmware I had no problems so I was thinking about an incompatibility. I haven't tried any gcode just loaded filaments. I also tried to reset the mmu but it doesn't change.
What can I try in your opinion?

**Comment by vertigo235** [comment]
How are you trying to load filament 5?  With the buttons on the MMU?  I do not have this issue you are experiencing.  Which MMU firmware are you using, I'm using 1.0.5 the latest posted by Prusa.

**Comment by GigiGipo** [comment]
I'm loading from lcd. 1.0.5

**Comment by vertigo235** [comment]
It looks like it's this bug from the Prusa FW 

https://github.com/prusa3d/Prusa-Firmware/pull/1886

**Comment by vertigo235** [comment]
I do not think this is even in the builds I'm sharing here, I'm basing the LA15 on the 3.7.1 TAG, and I think this bug was introduced after that.  Are you sure you are experiencing this with the latest build found in releases?

**Comment by vertigo235** [comment]
Anyhow, regardless this is not related to the LA1.5 code so I'm closing this issue.

**Comment by GigiGipo** [comment]
Ok thanks
