### ISSUE TITLE
MK3 BMG 0.9

### ISSUE THREAD

**Issue by J-Hutt** [vertigo235/Build-Prusa-LA-15#5]

**Comment by J-Hutt** [comment]
For the latest release (LA 1.5 Rebased on 3.7.2 RC1) - with an MK3 + BMG + 0.9 stepper, what would I set the microstepping resolution to, and then what e-steps?

**Comment by vertigo235** [comment]
I would use 
M350 E8
M92 E415

**Comment by J-Hutt** [comment]
Thanks for that, will give it a go.
