### ISSUE TITLE
new M600

### ISSUE THREAD

**Issue by brinkeb** [vertigo235/Build-Prusa-LA-15#6]
Hi! Since Prusa has modified the "M600"- code (Z_MAX_POS < 255 - FILAMENTCHANGE_ZADD) compiling fails if Z-height is higher than 255mm. Any chance to fix this? Thank you in advance!

**Comment by vertigo235** [comment]
Yes I have been meaning to look at this

**Comment by Lino77** [comment]
My printer has a Z high of 355 i have change in fsensor.cpp line 546 and marlin_main,cpp line 3004 from 255 to 400 just increase it by 45 

fsensor.cpp line 546
static_assert(Z_MAX_POS < (400 - FILAMENTCHANGE_ZADD), "Z-range too high, change fsensor_clamp_z<uint8_t> to <uint16_t>");

marlin_main,cpp line 3004
static_assert(Z_MAX_POS < (400 - FILAMENTCHANGE_ZADD), "Z-range too high, change the T type from uint8_t to uint16_t");

**Comment by vertigo235** [comment]
Fixed with PR #7 	

Thanks @Lino77
