### ISSUE TITLE
Powering off normally results in a beep

### ISSUE THREAD

**Issue by yamanub** [vertigo235/Build-Prusa-LA-15#8]
Hello, 
I just installed the new MK3S Bondtech extruder last night on my mostly stock MK3S and loaded the FW372-Build1562187288-1_75mm_MK3S-Bondtech-16-EINSy10a-E3Dv6full.hex from the latest Variant release. Everything calibrated fine and seems to be working so far but when I power down the printer I get a beep. I thought I remembered seeing a post about it but I cannot find an explanation or fix. Any ideas?

**Comment by wavexx** [comment]
There's now a beep, but only when power-panic is triggered. This happens when the power is cut without using the printer's switch.

Is this the case?

**Comment by yamanub** [comment]
ahh, that might be the case. I am using a remote power switch to disconnect power and not the actual switch on the PSU. I will check tonight and see if the units beeps when using the actual power switch. Since I log in and remotely power on or off using the smart switch is it a problem if I keep using it?

**Comment by wavexx** [comment]
Aside from the beep there should be no other side effect.

**Comment by wavexx** [comment]
See: https://github.com/prusa3d/Prusa-Firmware/issues/1929
This will be fixed in the next FW release.

**Comment by yamanub** [comment]
Yep. That's it. Thanks for quick response.
