### ISSUE TITLE
I can't compile the new release 3.8.0 RC1+ - fix PSU

### ISSUE THREAD

**Issue by MarcoZ76** [vertigo235/Build-Prusa-LA-15#9]
Hi!   i tried to compile this release on my mac with Arduino 1.8.5 but it give me some errors and i can't compile.
The error is:  
Archiving built core (caching) in: /var/folders/c5/bkdpvsls36j5ttvjwlv0c51m0000gn/T/arduino_cache_641072/core/core_rambo_avr_rambo_c3c3f6ee23766c41cb047dd9e72a7fbd.a
wiring.c.o (symbol from plugin): In function `__vector_23':
(.text+0x0): multiple definition of `__vector_23'
sketch/heatbed_pwm.cpp.o (symbol from plugin):(.text+0x0): first defined here
/Users/Marco/Library/Arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/../lib/gcc/avr/5.4.0/../../../../avr/bin/ld: Disabling relaxation: it will not work with multiple definitions
collect2: error: ld returned 1 exit status
exit status 1

I tried to compile other your release (like 3.7.2 more variant edition) immediately after this error and i can compile without errors.

What i have to do?
Thanks in advance

**Comment by vertigo235** [comment]
Sorry, I do not use Arduino to compile.  I set up a build pipeline using Drone CI (Ubuntu 64 enviornent) and the PF-Build.sh script by @3d-gussner 	

I did this so I wouldn't have to bother with Arduino :D , and it enabled me to build all the variants automatically.

**Comment by MarcoZ76** [comment]
Ohh noooo!!!! How can i modify the Z axis?  i have a strange setup of my printer that i need to use 200 instead of 210 or 204 for mk3s..... it's a pity......

**Comment by vertigo235** [comment]
It's a define parameter in the variant file
